# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_auto_20170703_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('line_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('correct', models.CharField(max_length=100)),
                ('wrong', models.CharField(max_length=100)),
                ('request_id', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_wordgaps_errors', to='core.User')),
            ],
            options={
                'get_latest_by': 'datetime',
            },
        ),
    ]
