# Generated by Django 2.0.5 on 2018-08-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('wordtype', models.CharField(max_length=100)),
                ('definition', models.TextField(null=True)),
            ],
            options={
                'db_table': 'definitions',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('line', models.IntegerField()),
                ('correct', models.CharField(max_length=100)),
                ('wrong', models.CharField(max_length=100)),
                ('request_id', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'datetime',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('line_id', models.IntegerField()),
                ('text', models.TextField()),
                ('difficulty', models.IntegerField()),
            ],
            options={
                'db_table': 'line',
            },
        ),
        migrations.CreateModel(
            name='LineWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('line_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('original', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(null=True)),
                ('definition', models.TextField(null=True)),
                ('pos', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'line_word',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=255, unique=True)),
                ('default_value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserLastLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('line', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='lineword',
            index_together={('content_id', 'line_id')},
        ),
        migrations.AddField(
            model_name='error',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
