# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('line', models.IntegerField()),
                ('correct', models.CharField(max_length=100)),
                ('wrong', models.CharField(max_length=100)),
                ('datetime', models.DateField()),
            ],
        ),
    ]
