# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
