# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160926_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='request_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
