# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_setting_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='setting',
            name='hr_setting_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
