# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161017_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_value',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
