# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_setting_default_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='hr_setting_name',
        ),
    ]
