# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161017_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='setting_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
