# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161017_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('line', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
