# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userlastline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'get_latest_by': 'datetime'},
        ),
    ]
