# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_content_definitions_line_lineword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lineword',
            options={},
        ),
    ]
